#spring.application.name=database_example

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:crypto-labs
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  application:
    name: database_example
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

